name: Build and test Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-and-test:
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    name: Check and test
    uses: greenbone/workflows/.github/workflows/ci-python.yml@main
    with:
      lint-packages: autohooks tests
      python-version: ${{ matrix.python-version }}

  codecov:
    name: Upload coverage to codecov.io
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          python-version: "3.10"
          token: ${{ secrets.CODECOV_TOKEN }}

  check-version:
    name: Check versioning for consistency
    uses: greenbone/workflows/.github/workflows/check-version.yml@main
